#数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysqlcrm?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    #设置访问路径
#  mvc:
#    view:
#      prefix: /webapp/
#      suffix: .jsp
#Mybaits---mapper扫描路径
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  
logging:
  level:
    com.st.dao: debug